
# Configuration values for deployment.yaml
replicaCount: 2
image:
  repository: 123456789.dkr.ecr.us-east-1.amazonaws.com/document-processor
  tag: "latest"
  pullPolicy: IfNotPresent

# Service account with IRSA annotation for serviceaccount.yaml
serviceAccount:
  create: true
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/document-processor-dev-role>

# Configuration values for configmap.yaml
config:
  s3Bucket: document-processor-dev-bucket
  sqsQueueUrl: https://sqs.us-east-1.amazonaws.com/123456789/document-processor-dev-queue
  logLevel: INFO
  awsRegion: us-east-1

# Autoscaling configuration for hpa.yaml
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Prometheus Rule configuration for prometheusrule.yaml
monitoring:
  enabled: true
  alerts:
    errorRateThreshold: 5
    queueDepthThreshold: 1000

# Resource requests/limits defined
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 512Mi

# Liveness and readiness probes


# Environment variables from ConfigMap and Secrets
envFrom:
  - configMapRef:
      name: document-processor-config
  - secretRef:
      name: document-processor-secret



# Security context (non-root, read-only filesystem)
securityContext: 
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

