# Service account with IRSA annotation for serviceaccount.yaml
serviceAccount:
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/document-processor-staging-role
    
# Configuration values for configmap.yaml
config:
  s3Bucket: document-processor-staging-bucket
  sqsQueueUrl: https://sqs.us-east-1.amazonaws.com/123456789/document-processor-staging-queue