apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "document-processor.fullname" . }}
  labels:
    {{- include "document-processor.labels" . | nindent 4 }}
data:
  S3_BUCKET_NAME: {{ .Values.config.s3Bucket | quote }}
  SQS_QUEUE_URL: {{ .Values.config.sqsQueueUrl | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  