apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-processor.fullname" . }}
  labels:
    {{- include "document-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "document-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "document-processor.labels" . | nindent 8 }}
    spec:

      serviceAccountName: {{ include "document-processor.serviceAccountName" . }}

      securityContext: 
        runAsNonRoot: true
        runAsUser: 1000

      containers:
        - name: {{ include "document-processor.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort:
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          envFrom:
            - configMapRef:
                name: {{ include "document-processor.fullname" . }}-config
            - secretRef:
                name: {{ include "document-processor.fullname" . }}-secret

          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http