apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "document-processor.fullname" . }}
  labels:
    {{- include "document-processor.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  seelector:
    matchLabels:
      {{- include "document-processor.selectorLabels" . | nindent 6 }}