{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "document-processor.serviceAccountName" . }}
  labels:
    {{- include "document-processor.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ index .Values.serviceAccount.annotations "eks.amazonaws.com/role-arn" }}
{{- end }}
